In [73]:
import haliax as hax
Batch = hax.Axis("batch_size", 32)
Vocab = hax.Axis("vocab_size", 64)


In [72]:
pred = jnp.array([[0.1, 0.3, 0.25, 0.35], [0.1, 0.3, 0.25, 0.35]] )
label = jnp.array([[0, 0, 1, 0], [1,0,0,0]])

jnp.take_along_axis(pred, label, axis=0)

Array([[0.1 , 0.3 , 0.25, 0.35],
       [0.1 , 0.3 , 0.25, 0.35]], dtype=float32)

NameError: name 'Array' is not defined

In [62]:
import jax.numpy as jnp
import jax.random as jrandom
from jax.random import PRNGKey

# predict y from x using  a linear model (W)
x = jrandom.uniform(PRNGKey(0), (128, 64))
y = jrandom.uniform(PRNGKey(1), (128,))
W = jrandom.uniform(PRNGKey(2), (64, 1))

def mse(pred, target):
    return jnp.mean((pred - target) * (pred - target) )

y_pred = x @ W
# y_pred = jnp.dot(x, W)
mse(y_pred, y)

Array(225.61096, dtype=float32)

In [63]:
import haliax as hax

In [66]:
y_pred

Array([[16.13712  ],
       [14.340529 ],
       [16.73117  ],
       [15.724411 ],
       [14.94077  ],
       [15.615004 ],
       [15.010483 ],
       [14.150351 ],
       [17.787096 ],
       [16.79407  ],
       [17.738586 ],
       [16.171154 ],
       [15.861052 ],
       [15.688703 ],
       [15.544219 ],
       [14.969957 ],
       [15.00909  ],
       [18.886345 ],
       [15.104877 ],
       [15.535769 ],
       [15.091652 ],
       [16.396854 ],
       [14.758905 ],
       [14.841494 ],
       [15.152203 ],
       [14.573544 ],
       [14.6982765],
       [14.312476 ],
       [18.870256 ],
       [17.38173  ],
       [15.795318 ],
       [14.836987 ],
       [15.09288  ],
       [14.492235 ],
       [14.954269 ],
       [15.316652 ],
       [15.250214 ],
       [15.428728 ],
       [16.857693 ],
       [14.818967 ],
       [15.6635475],
       [14.149357 ],
       [14.682432 ],
       [17.175083 ],
       [15.206553 ],
       [15.857845 ],
       [14.923263 ],
       [16.67

In [67]:
y

Array([0.5267161 , 0.475595  , 0.8405764 , 0.9995277 , 0.88668406,
       0.7873306 , 0.03294337, 0.8513657 , 0.2201314 , 0.25549543,
       0.8181137 , 0.9088943 , 0.89237475, 0.5393442 , 0.10628283,
       0.48869777, 0.98352754, 0.8604953 , 0.32526028, 0.2016089 ,
       0.99280465, 0.18507946, 0.45113742, 0.589748  , 0.379364  ,
       0.9170332 , 0.65429974, 0.2337588 , 0.7278191 , 0.6063702 ,
       0.9531244 , 0.60851586, 0.15228295, 0.48279357, 0.512818  ,
       0.6131208 , 0.4723873 , 0.13501418, 0.08134079, 0.3154415 ,
       0.68261135, 0.7209277 , 0.6769662 , 0.04877925, 0.5989431 ,
       0.20004189, 0.2850877 , 0.41925347, 0.79260445, 0.02059197,
       0.6117219 , 0.5591594 , 0.6735512 , 0.56520104, 0.69178665,
       0.1353091 , 0.4898429 , 0.1187048 , 0.9715196 , 0.31834257,
       0.38521683, 0.5032133 , 0.2881428 , 0.10336947, 0.9012755 ,
       0.81640387, 0.99545324, 0.84138227, 0.8136288 , 0.08803821,
       0.28426075, 0.7046361 , 0.654268  , 0.800683  , 0.23390

In [68]:
y_pred - y

Array([[15.610403 , 15.661524 , 15.296543 , ..., 15.612529 , 15.777923 ,
        15.832141 ],
       [13.813813 , 13.864935 , 13.499953 , ..., 13.815939 , 13.981333 ,
        14.035551 ],
       [16.204454 , 16.255575 , 15.8905945, ..., 16.206581 , 16.371973 ,
        16.426193 ],
       ...,
       [14.264408 , 14.315529 , 13.950548 , ..., 14.266534 , 14.431928 ,
        14.486146 ],
       [15.606688 , 15.657808 , 15.292828 , ..., 15.608813 , 15.774207 ,
        15.828425 ],
       [15.878023 , 15.929144 , 15.564163 , ..., 15.880149 , 16.045542 ,
        16.099762 ]], dtype=float32)